# Generated by Django 2.1.7 on 2019-02-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('votes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
