# Generated by Django 2.1.7 on 2019-03-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_remove_menu_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='votes',
            new_name='likes',
        ),
    ]
