# Generated by Django 2.1.7 on 2019-03-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_auto_20190301_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='likes',
            new_name='votes',
        ),
    ]
