# Generated by Django 2.1.7 on 2019-03-05 06:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_auto_20190301_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('like_status', models.BooleanField(default=False)),
                ('date_liked', models.DateField(default=datetime.date.today)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.Menu')),
            ],
        ),
    ]
